### PR TITLE
Fix test parsing when class and superclass are located in different dex files (fixes #45)

### LINKED ISSUE #45: Multidex abstract test class issue
Hi,
We use this library for extracting tests to run from apks and we have recently noticed that parsed test count is not stable. We run it on CI and sometimes a few test methods are not parsed. After some investigation, it turns out that these methods are defined in base test classes.

I checked two apks: the first one where we don't have tests from a base class and the second one where these tests were parsed successfully. Hashes of the apks are different but if you unpack them and compare the hashes of the contents they are absolutely identical. Hashes of all the dex files are the same. The only difference that I found is the order of dex files how they appear in zip archive :)

So the problem is that base class was defined in `classes4.dex` and the concrete implementation is in `classes2.dex`. The order of the dex files in the archive is completely random each time when you package the apk. Not sure is this a violation of dex specification or not because in the [specs](https://source.android.com/devices/tech/dalvik/dex-format.html) there is no info about multidex and I can't find any specs specifically for multidex. 

We use AGP 3.5.1. Has anyone encountered this problem?
Looks like we can't rely on the order of classes/superclasses when we have multiple dex files, so we need to have multiple passes. What do you think about it? I will create a PR soon with the fixes

### PR DESCRIPTION
**Pull request by lukaville**
See #45 for more info

### CODE REVIEW

File: test-app/src/androidTest/java/com/linkedin/parser/test/junit4/java/FloatRange.java [hunk 1]
```diff
@@ -7,9 +7,9 @@
 import static java.lang.annotation.ElementType.LOCAL_VARIABLE;
 import static java.lang.annotation.ElementType.METHOD;
 import static java.lang.annotation.ElementType.PARAMETER;
-import static java.lang.annotation.RetentionPolicy.CLASS;
+import static java.lang.annotation.RetentionPolicy.RUNTIME;
 
-@Retention(CLASS)
+@Retention(RUNTIME)
```
Comment (lukaville) [inline test-app/src/androidTest/java/com/linkedin/parser/test/junit4/java/FloatRange.java:12]: with the new build tools, annotations with `CLASS` retention are not included in the target dex file

File: parser/src/main/kotlin/com/linkedin/dex/parser/JUnit4Extensions.kt [hunk 2]
```diff
@@ -84,28 +112,58 @@ private fun DexFile.getSuperclassName(classDefItem: ClassDefItem): String {
...
+            val dexFile = parsingResult.dexFile
+
+            val superTestMethods = getSuperTestMethods(classTestMethods, parsingResult.superClassName)
+            val superSuperTestMethods = classTestMethods[parsingResult.superClassName]
+                    ?.superClassName
+                    ?.let { classTestMethods[it] }
+                    ?.let { createTestMethodsFromSuperMethods(it, classTestMethods, classAllTestMethods) }
+                    ?: emptySet()
+
+            val testMethods = superTestMethods + superSuperTestMethods
```
Comment (Litun) [inline parser/src/main/kotlin/com/linkedin/dex/parser/JUnit4Extensions.kt]: Let's move recursion by one step. We can make it simpler if we work only with current and super

File: parser/src/main/kotlin/com/linkedin/dex/parser/JUnit4Extensions.kt [hunk 3]
```diff
@@ -16,47 +16,75 @@ import com.linkedin.dex.spec.MethodIdItem
...
-            val superTests = createTestMethodsFromSuperMethods(dexFile, classDef, dexFile.formatClassName(classDef), getSuperTestMethods(classDef, classTestMethods, dexFile))
-            classTestMethods[dexFile.getClassName(classDef)] = ClassParsingResult(dexFile.getSuperclassName(classDef), baseTests union superTests, !(isAbstract(classDef) || isInterface(classDef)))
-        }
-    }
+    classTestMethods
+            .keys
+            .forEach { key ->
+                classTestMethods.computeIfPresent(key) { _, value ->
+                    val testMethods = createTestMethodsFromSuperMethods(value, classTestMethods, classAllTestMethods)
+                    value.copy(testMethods = value.testMethods union testMethods)
```
Comment (Litun) [inline parser/src/main/kotlin/com/linkedin/dex/parser/JUnit4Extensions.kt]: I think it's better to keep classTestMethods immutable

**Review by Litun — CHANGES_REQUESTED** [review]

File: parser/src/main/kotlin/com/linkedin/dex/parser/JUnit4Extensions.kt (hunk 2 above)
Comment (lukaville) [reply parser/src/main/kotlin/com/linkedin/dex/parser/JUnit4Extensions.kt]: sounds good 👍

File: parser/src/main/kotlin/com/linkedin/dex/parser/JUnit4Extensions.kt (hunk 3 above)
Comment (lukaville) [reply parser/src/main/kotlin/com/linkedin/dex/parser/JUnit4Extensions.kt]: 👍

**Review by Litun — APPROVED** [review]

**Review by yufimtsev — APPROVED** [review]

File: build.gradle [hunk 4]
```diff
@@ -1,19 +1,19 @@
...
-        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4'
-        classpath 'org.jfrog.buildinfo:build-info-extractor-gradle:4.4.0'
-        classpath 'com.github.jengelman.gradle.plugins:shadow:1.2.4'
-        classpath 'org.jetbrains.dokka:dokka-gradle-plugin:0.9.9'
-        classpath 'com.android.tools.build:gradle:2.3.0'
+        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.8.4'
+        classpath 'com.vanniktech:gradle-maven-publish-plugin:0.8.0'
+        classpath 'org.jfrog.buildinfo:build-info-extractor-gradle:4.11.0'
+        classpath 'com.github.jengelman.gradle.plugins:shadow:5.1.0'
+        classpath 'com.android.tools.build:gradle:3.5.3'
```
Comment (kkoser) [inline build.gradle]: Unless these are needed to get the publication,  i would recommend removing them, just because we don't know all the details of what has changed, and these plugins are very hard to test without actually publishing artifacts.

File: buildSrc/build.gradle [hunk 5]
```diff
@@ -11,9 +11,10 @@ dependencies {
...
     compile localGroovy()
 
-    compile 'org.ajoberstar:gradle-git:1.2.0'
-    compile group: 'org.apache.httpcomponents', name: 'fluent-hc', version: '4.5.2'
-    compile('org.jfrog.buildinfo:build-info-extractor-gradle:4.8.1') {
+    compile 'org.ajoberstar:gradle-git:1.7.2'
+    compile group: 'org.apache.httpcomponents', name: 'fluent-hc', version: '4.5.10'
+    compile('org.jfrog.buildinfo:build-info-extractor-gradle:4.11.0') {
         exclude module: 'groovy-all'
+        exclude module: 'commons-io'
```
Comment (kkoser) [inline buildSrc/build.gradle]: some comment in here on versions related to publihsing stuff (which should be everything in buildsrc)

File: parser/build.gradle [hunk 6]
```diff
@@ -83,7 +83,7 @@ build.dependsOn shadowJar
 task testParsing(dependsOn: ':test-app:assembleDebugAndroidTest', type: JavaExec) {
     classpath sourceSets.main.runtimeClasspath
     main = 'com.linkedin.dex.parser.DexParser'
-    args "${rootProject.project('test-app').buildDir}/outputs/apk/test-app-debug-androidTest.apk", "$buildDir"
+    args "${rootProject.project('test-app').buildDir}/outputs/apk/androidTest/debug/test-app-debug-androidTest.apk", "$buildDir"
```
Comment (kkoser) [inline parser/build.gradle]: just double checking - this is a result of the bumps in AGP/Gradle moving the default output directory correct?

**Review by kkoser — CHANGES_REQUESTED** [review]
Logic lgtm, so sorry for the delay!! Unless we need the publication stuff I commented on, I'd revert that, but otherwise LGTM

File: parser/build.gradle (hunk 6 above)
Comment (lukaville) [reply parser/build.gradle]: yep, the new Android Gradle Plugin generates android test apk in `androidTest/debug` directory

File: build.gradle (hunk 4 above)
Comment (lukaville) [reply build.gradle]: we need to update these dependencies to use them with the new Android Gradle Plugin (old versions of them are not compatible with the new AGP)

Comment (lukaville) [reply build.gradle]: do you want me to revert updating AGP?

Comment (kkoser) [reply build.gradle]: Hi, apologies again for the delay here. I think we should probably drop this part - I tried testing out publishing flow locally with these changes, and hit some dependency issuese resulting in failures (`Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.IOUtils` from within the artifactory client). I know the publishing flow is hard to test, so I'm thinking its probably easier for this change to just focus on the functional change. Are you ok with that?

**Review by kkoser — APPROVED** [review]

File: build.gradle (hunk 4 above)
Comment (kkoser) [reply build.gradle]: Thanks!
