### PR TITLE
Fix #21 bufferoverflow when parsing test annotations

### LINKED ISSUE #21: BufferOverflowException running parser
When using this library on a test APK I have the following error:

```bash
Exception in thread "main" java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:521)
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:169)
	at com.linkedin.dex.spec.EncodedValue$Companion.getPaddedBufferToTheRight(EncodedValue.kt:116)
	at com.linkedin.dex.spec.EncodedValue$Companion.create(EncodedValue.kt:62)
	at com.linkedin.dex.spec.AnnotationElement.<init>(AnnotationElement.kt:13)
	at com.linkedin.dex.spec.EncodedAnnotation$Companion.create(EncodedAnnotation.kt:18)
	at com.linkedin.dex.spec.AnnotationItem$Companion.create(AnnotationItem.kt:17)
	at com.linkedin.dex.parser.AnnotationUtilsKt.getMethodAnnotationValues(AnnotationUtils.kt:60)
	at com.linkedin.dex.parser.TestMethodKt.createTestMethod(TestMethod.kt:53)
	at com.linkedin.dex.parser.TestMethodKt.createTestMethods(TestMethod.kt:46)
	at com.linkedin.dex.parser.JUnit4ExtensionsKt.findAllJUnit4Tests(JUnit4Extensions.kt:35)
	at com.linkedin.dex.parser.DexParser$Companion.findTestMethods(DexParser.kt:60)
	at com.linkedin.dex.parser.DexParser$Companion.findTestNames(DexParser.kt:45)
	at com.linkedin.dex.parser.DexParser$Companion.main(DexParser.kt:36)
	at com.linkedin.dex.parser.DexParser.main(DexParser.kt)
```

Investigating this issue, I found this [function][function].

```kotlin
private fun getPaddedBufferToTheRight(byteBuffer: ByteBuffer, size: Int, fullSize: Int): ByteBuffer
```

It allocates a `HeapByteBuffer` with capacity equals `fullSize` value.
What is a problem when the value of variable `size` is negative, because in this [line][function-for] it will try to put `(fullSize - size)` bytes, inside for-loop.

**For instance**:

In my case, the function `getPaddedBufferToTheRight` was called with values: 
- `size` = -3
- `fullSize` = 8

It will allocate a `HeapByteBuffer` with capacity 8, but it will try to put 11 bytes, because `for (x in size + 1..fullSize)`.

**Possible solution**:

This issue can be fixed by changing the capacity of the buffer.

Instead of capacity equals `fullSize`:

```kotlin
val buffer = ByteBuffer.allocate(fullSize)
```

We can change this code to adjust the capacity, using the `size` variable too:

```kotlin
val capacity = fullSize + Math.abs(Math.min(size, 0))
val buffer = ByteBuffer.allocate(capacity)
```

This approach just will ignore the annotation attribute value, that will be filled with zero. :/

**Update**:

This problem occurs due to the use of [CircularProgressBar][circular-progress-bar] library.
It defines the method [getBackgroundStrokeWidth][cpb-function] that has the annotation [@FloatRange][float-range-source-code].
This annotation defines four attributes, where two of them are double (`from` and `to`), but in the [library][cpb-function-annotation], it uses the annotation as a float with `Float.MAX_VALUE`, what causes the issue.

The problem only occurs if we use the constants `Float.MAX_VALUE` or `Double.MAX_VALUE`.

[function]: https://github.com/linkedin/dex-test-parser/blob/master/parser/src/main/kotlin/com/linkedin/dex/spec/EncodedValue.kt#L107
[function-for]: https://github.com/linkedin/dex-test-parser/blob/master/parser/src/main/kotlin/com/linkedin/dex/spec/EncodedValue.kt#L112
[circular-progress-bar]: https://github.com/yuriy-budiyev/circular-progress-bar
[cpb-function]: https://github.com/yuriy-budiyev/circular-progress-bar/blob/cc4576a0f6484c6419e87ebc31e5a9f5e583f255/src/main/java/com/budiyev/android/circularprogressbar/CircularProgressBar.java#L358
[cpb-function-annotation]: https://github.com/yuriy-budiyev/circular-progress-bar/blob/cc4576a0f6484c6419e87ebc31e5a9f5e583f255/src/main/java/com/budiyev/android/circularprogressbar/CircularProgressBar.java#L357
[float-range-source-code]: https://android.googlesource.com/platform/frameworks/support/+/3d9b382/annotations/src/android/support/annotation/FloatRange.java#40

### PR DESCRIPTION
**Pull request by kkoser**
We should never have been seeing negative values for the size of annotations, as the byte that they
are stored in is unsigned. However, in the process of converting the byte to an int (kotlin has no
bitwise operators available to byte types), we were padding with a bunch of 1s causing it to be read
as a signed number. Forcing it down to an unsigned 8 bit value resolves this issue and lets us read the
values out correctly.

### CODE REVIEW

**Review by cckroets — APPROVED** [review]

File: parser/src/main/kotlin/com/linkedin/dex/spec/EncodedValue.kt [hunk 1]
```diff
@@ -126,3 +126,5 @@ sealed class EncodedValue {
         }
     }
 }
+
+private fun Int.toUnsigned8BitInt(): Int = (this and 0xFF)
```
Comment (drewhannay) [inline parser/src/main/kotlin/com/linkedin/dex/spec/EncodedValue.kt]: Let's put this on `Byte` instead of `Int` to make the call site slightly clearer
